name: CI-CD

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string

env:
  CF_DEPLOY_APPS: 'neoavath'
  AWS_EC2_DEPLOY_APPS: 'df-auction-crawling'

jobs:
  router:
    runs-on: ubuntu-latest
    steps:
      - name: Determine Deployment Type
        id: determine-type
        run: |

          echo "inputs.target: ${{ inputs.target }}"

          # CF_DEPLOY_APPS에 포함된 앱인 경우 CF 워크플로우 실행
          if [[ "${{ env.CF_DEPLOY_APPS }}" == *"${{ inputs.target }}"* ]]; then
            echo "workflow=CF" >> $GITHUB_OUTPUT
          # AWS_EC2_DEPLOY_APPS에 포함된 앱인 경우 AWS-EC2 워크플로우 실행
          elif [[ "${{ env.AWS_EC2_DEPLOY_APPS }}" == *"${{ inputs.target }}"* ]]; then
            echo "workflow=AWS-EC2" >> $GITHUB_OUTPUT
          else
            echo "No matching deployment type found for ${{ inputs.target }}"
            exit 1
          fi

  cloudflare-workflow:
    needs: router
    if: needs.router.outputs.workflow == 'CF'
    uses: ./.github/workflows/02-01.CI-CD(CF).yml
    with:
      target: ${{ inputs.target }}
    secrets: inherit

  aws-ec2-workflow:
    needs: router
    if: needs.router.outputs.workflow == 'AWS-EC2'
    uses: ./.github/workflows/02-02.CI-CD(AWS-EC2).yml
    with:
      target: ${{ inputs.target }}
    secrets: inherit
